# Generated by Django 4.0.4 on 2022-06-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('Midterm', 'Midterm'), ('Final', 'Final')], max_length=50)),
                ('start_date', models.DateTimeField()),
            ],
        ),
    ]
