# Generated by Django 4.0.4 on 2022-06-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='end_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
