# Generated by Django 4.0.4 on 2022-06-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_exam_duration_exam_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('Midterm', 'Midterm'), ('Final', 'Final'), ('Make-up', 'Make-up')], max_length=50),
        ),
    ]
