# Generated by Django 4.1.7 on 2023-05-22 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_alter_exam_exam_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invigilator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='InvigilatorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
                ('invigilator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.invigilator')),
            ],
            options={
                'unique_together': {('exam', 'invigilator')},
            },
        ),
        migrations.AddField(
            model_name='invigilator',
            name='availability',
            field=models.ManyToManyField(through='exam.InvigilatorAssignment', to='exam.exam'),
        ),
    ]
