# Generated by Django 4.1.7 on 2023-05-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_exam_language_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='language_level',
            field=models.CharField(choices=[('0', '0% English'), ('30', '30% English'), ('100', '100% English')], default='0', max_length=3),
        ),
    ]
