# Generated by Django 4.1.7 on 2023-05-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_alter_exam_language_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='education_type',
            field=models.CharField(choices=[('1', '1. Öğretim'), ('2', '2. Öğretim')], default='1', max_length=1),
        ),
    ]
