# Generated by Django 4.1.7 on 2023-05-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_exam_education_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('Midterm', 'Midterm'), ('Final', 'Final')], max_length=50),
        ),
    ]
