# Generated by Django 4.1.7 on 2023-05-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_course_student_count'),
        ('exam', '0010_alter_exam_exam_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='location',
        ),
        migrations.AddField(
            model_name='exam',
            name='locations',
            field=models.ManyToManyField(related_name='exams', to='university.classroom'),
        ),
    ]
