# Generated by Django 4.1.7 on 2023-05-31 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_remove_exam_location_exam_locations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='locations',
            new_name='location',
        ),
    ]
