# Generated by Django 4.0.4 on 2022-06-04 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='slug',
        ),
    ]
