# Generated by Django 4.1.7 on 2023-05-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_unit_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='student_count',
            field=models.IntegerField(default=0),
        ),
    ]
